# Generated by Django 4.1 on 2023-10-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_bookinstance_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="lang",
        ),
        migrations.AddField(
            model_name="book",
            name="lang",
            field=models.ForeignKey(
                help_text="Select a language for this book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.lang",
            ),
        ),
    ]
